name: Quality checks

on:
  push:
    branches:
      - main

env:
  APP_URL: http://localhost:3000
  NEXT_PUBLIC_API_URL: http://localhost:3101
  NEXT_PUBLIC_CHAT_SOCKET_URL: ws://localhost:3101/chat

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install
        run: npm ci

      - name: Run Lint
        run: npm run lint

      - name: Run Prettier Check
        run: npm run prettier-check

      - name: Build
        run: npm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run E2E Tests
        run: npx run test:e2e
